
FROM golang:1.26.3 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /app/urlshortener
FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /app /app
CMD ["/app"]


